.github/workflows/release.yml, .github/workflows/test.yml, pom.xml
Signed-off-by: Florin Hillebrand <florin.hillebrand@tuwien.ac.at>
=> [CI] Fix workflow permissions and URLs in POM.

.github/workflows/test.yml, README.md
Signed-off-by: Florin Hillebrand <florin.hillebrand@tuwien.ac.at>
=> [CI] Add Sonar analysis.

.github/workflows/test.yml
Signed-off-by: Florin Hillebrand <florin.hillebrand@tuwien.ac.at>
=> [CI] Add Github token to sonar stage environment.

src/main/java/at/ac/tuwien/damap/rest/dmp/domain/DmpDO.java, src/main/java/at/ac/tuwien/damap/rest/dmp/mapper/ProjectSupplementDOMapper.java, src/main/java/at/ac/tuwien/damap/rest/dmp/service/DmpService.java
=> [task] cris boolean values should always show the projects settings,

src/main/java/at/ac/tuwien/damap/rest/dmp/mapper/DmpDOMapper.java
=> [bugfix] fix distributions being deleted at every save,

docker/docker-compose.yaml, docker/nginx.conf, docker/sample-damap-realm-export.json, src/main/java/at/ac/tuwien/damap/rest/ConfigResource.java, src/main/resources/application.yaml
=> [task] update docker-compose setup,

src/main/java/at/ac/tuwien/damap/rest/dmp/service/DmpConsistencyUtility.java, src/main/java/at/ac/tuwien/damap/rest/dmp/service/DmpService.java, src/test/java/at/ac/tuwien/damap/rest/dmp/DmpConsistencyUtilityTest.java
=> Add DMP consistency utility

src/main/java/at/ac/tuwien/damap/rest/dmp/service/DmpConsistencyUtility.java
* Decouple DataRightsAndAccessControl and LegalRestrictions values
* Set DataGeneration for new datasets only
refs #79677
=> Dataset Changes

src/main/java/at/ac/tuwien/damap/conversion/AbstractTemplateExportScienceEuropeComponents.java, src/main/java/at/ac/tuwien/damap/conversion/AbstractTemplateExportSetup.java, src/main/java/at/ac/tuwien/damap/rest/dmp/service/DmpService.java
=> [bugfix] nullpointer on export using manual input projects,

src/main/java/at/ac/tuwien/damap/rest/dmp/domain/DatasetDO.java, src/main/java/at/ac/tuwien/damap/rest/dmp/domain/DmpDO.java, src/main/java/at/ac/tuwien/damap/rest/dmp/domain/ProjectDO.java, src/main/java/at/ac/tuwien/damap/rest/openaire/mapper/OpenAireMapper.java, src/main/resources/db/changeLog.yaml
=> change VARCHAR2 to CLOBs for description properties 

src/main/java/at/ac/tuwien/damap/rest/AccessResource.java, src/main/java/at/ac/tuwien/damap/rest/access/service/AccessService.java, src/main/java/at/ac/tuwien/damap/validation/AccessValidator.java
proposed adjustment to dmp access method
=> proposed change for dmp access canGetAccess method

src/main/java/at/ac/tuwien/damap/rest/AccessResource.java, src/main/java/at/ac/tuwien/damap/rest/access/domain/AccessDO.java, src/main/java/at/ac/tuwien/damap/rest/access/mapper/AccessMapper.java, src/main/java/at/ac/tuwien/damap/rest/access/service/AccessService.java, src/main/java/at/ac/tuwien/damap/rest/dmp/mapper/MapperService.java, src/main/java/at/ac/tuwien/damap/validation/AccessValidator.java, src/test/java/at/ac/tuwien/damap/rest/AccessResourceTest.java
Feature
This PR adds an API that allows to add and remove editors for DMPs.
None
Permissions as described in GH-52
Frontend changes depending on this PR: https://github.com/tuwien-csd/damap-frontend/pull/70
closes GH-52
=> Add DMP editor functionality

pom.xml, src/main/java/at/ac/tuwien/damap/domain/Contributor.java, src/main/java/at/ac/tuwien/damap/domain/Cost.java, src/main/java/at/ac/tuwien/damap/domain/Dataset.java, src/main/java/at/ac/tuwien/damap/domain/DmpVersion.java, src/main/java/at/ac/tuwien/damap/domain/Host.java, src/main/java/at/ac/tuwien/damap/domain/InternalStorageTranslation.java, src/main/java/at/ac/tuwien/damap/enums/EAccessRight.java, src/main/java/at/ac/tuwien/damap/enums/EAgreement.java, src/main/java/at/ac/tuwien/damap/enums/EComplianceType.java, src/main/java/at/ac/tuwien/damap/enums/EContributorRole.java, src/main/java/at/ac/tuwien/damap/enums/ECostType.java, src/main/java/at/ac/tuwien/damap/enums/EDataAccessType.java, src/main/java/at/ac/tuwien/damap/enums/EDataKind.java, src/main/java/at/ac/tuwien/damap/enums/EDataQualityType.java, src/main/java/at/ac/tuwien/damap/enums/EDataSource.java, src/main/java/at/ac/tuwien/damap/enums/EDataType.java, src/main/java/at/ac/tuwien/damap/enums/EFunctionRole.java, src/main/java/at/ac/tuwien/damap/enums/EFundingState.java, src/main/java/at/ac/tuwien/damap/enums/EIdentifierType.java, src/main/java/at/ac/tuwien/damap/enums/ESecurityMeasure.java, src/main/java/at/ac/tuwien/damap/enums/ETemplateType.java, src/main/java/at/ac/tuwien/damap/rest/access/domain/AccessDO.java, src/main/java/at/ac/tuwien/damap/rest/administration/domain/ConsentDO.java, src/main/java/at/ac/tuwien/damap/rest/dmp/domain/DatasetDO.java, src/main/java/at/ac/tuwien/damap/rest/dmp/domain/DmpDO.java, src/main/java/at/ac/tuwien/damap/rest/dmp/domain/DmpListItemDO.java, src/main/java/at/ac/tuwien/damap/rest/dmp/domain/ProjectDO.java, src/main/java/at/ac/tuwien/damap/rest/madmp/mapper/MaDmpMapper.java, src/main/java/at/ac/tuwien/damap/rest/version/VersionDO.java
Refactoring
Use jackson for JSON (de)serialization everywhere.
Tested with current version of `damap-frontend` and could not identify any issues in the UI.
closes GH-
=> Json (de)serialization

src/main/java/at/ac/tuwien/damap/rest/fits/mapper/FitsMapper.java
Bugfix
Set default values for uploaded datasets.
closes https://github.com/tuwien-csd/damap-frontend/issues/84
=> [Bugfix] Set dataset default values in FitsMapper

lombok.config, pom.xml, src/main/java/at/ac/tuwien/damap/annotations/gdpr/Gdpr.java, src/main/java/at/ac/tuwien/damap/annotations/gdpr/GdprBase.java, src/main/java/at/ac/tuwien/damap/annotations/gdpr/GdprContext.java, src/main/java/at/ac/tuwien/damap/annotations/gdpr/GdprExtended.java, src/main/java/at/ac/tuwien/damap/annotations/gdpr/GdprKey.java, src/main/java/at/ac/tuwien/damap/domain/Access.java, src/main/java/at/ac/tuwien/damap/domain/Consent.java, src/main/java/at/ac/tuwien/damap/domain/Contributor.java, src/main/java/at/ac/tuwien/damap/repo/GdprRepo.java, src/main/java/at/ac/tuwien/damap/rest/GdprResource.java, src/main/java/at/ac/tuwien/damap/rest/gdpr/domain/GdprQuery.java, src/main/java/at/ac/tuwien/damap/rest/gdpr/domain/GdprResult.java, src/main/java/at/ac/tuwien/damap/rest/gdpr/domain/HqlQuery.java, src/main/java/at/ac/tuwien/damap/rest/gdpr/exceptions/MissingGdprKeyException.java, src/main/java/at/ac/tuwien/damap/rest/gdpr/exceptions/NoSuchContextPropertyException.java, src/main/java/at/ac/tuwien/damap/rest/gdpr/service/GdprQueryUtil.java, src/main/java/at/ac/tuwien/damap/rest/gdpr/service/GdprService.java, src/main/java/at/ac/tuwien/damap/rest/gdpr/service/HqlQueryUtil.java, src/main/resources/application.yaml, src/test/java/at/ac/tuwien/damap/rest/GdprResourceTest.java, src/test/java/at/ac/tuwien/damap/service/GdprServiceTest.java
Feature
Adds annotations that mark GDPR related fields, and endpoint to retrieve data.
None
If there's an edge case, that is not covered properly.
closes GH-77
=> Add GDPR utility

src/main/java/at/ac/tuwien/damap/rest/persons/orcid/ORCIDExpandedSearchResult.java, src/main/java/at/ac/tuwien/damap/rest/persons/orcid/ORCIDPerson.java, src/main/java/at/ac/tuwien/damap/rest/persons/orcid/ORCIDPersonMapper.java, src/main/java/at/ac/tuwien/damap/rest/persons/orcid/ORCIDPersonServiceImpl.java, src/main/java/at/ac/tuwien/damap/rest/persons/orcid/OrcidPersonService.java
refactor/rename ORCID related files
Bugfix, Refactoring
Set university ID of ORCID person, as this is also used for front-end logic (e.g. selecting contact person).
Refactor/Rename ORCID related files to match ORCID API. Also eases reading and understanding the code.
Implement fetching a single person from ORCID by its orcid.
none
closes GH-
=> refactor ORCID related files

CUSTOMISING.md, INSTALLATION.md
Update customisation instruction to contain the new person service integration.
=> update customisation instructions

Dockerfile
Docker
With the latest java-11-openjdk version, `tzdata-java` package needs to be installed inside the container as it is required for quarkus. See also: https://github.com/quarkusio/quarkus/discussions/34907
=> docker: install tzdata-java package

docker/docker-compose.yaml, src/main/resources/application.yaml
config: set fits url
config: set request body limit for easier overview
Feature
This will add a default fits service to the docker-compose file, which will allow to test the FITS functionality.
A config for request max-body size has also been set, to provide an easy adaptation possibility. 
closes GH-
=> docker-services: add default fits service

docker/sample-damap-realm-export.json
Config
Added an admin user to sample-damap-realm-export.json to make testing easier.
closes GH-124
=> #124 - Added admin user

src/main/resources/application.yaml, src/test/java/at/ac/tuwien/damap/r3data/RepositoriesResourceTest.java, src/test/java/at/ac/tuwien/damap/util/TestDOFactory.java
Feature
Adds 4 sample repos to be returned by the backend.
closes GH-163
=> RepositoriesService: Make backend return sample repositories

docker/docker-compose.yaml, src/main/resources/application.yaml
Update services used in docker compose:
- keycloak: switched to `bitnami/keycloak:23` because `jboss/keycloak` is not available anymore. Newer versions of keycloak omit the `/auth` for the realm config - hence the change in `application.yaml`
- postgresql: updated to use version 16. Version 12 will see end of life in November this year (https://www.postgresql.org/support/versioning/)
closes GH-
=> docker: use current versions of images
